name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Boost
      run: sudo apt-get update && sudo apt-get install -y libboost-all-dev

    - name: Install Clang and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang

    - name: Make build.sh executable
      run: chmod +x ./build.sh

    - name: Run build script
      run: bash build.sh  --enable-unit-tests --enable-fuzzy-tests --enable-pef-accur-tests --clean
